name: CI production

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  release-to-github:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
